# ==============================
# docker-compose.yml (2 services)
# ==============================
version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: taxlaw_fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: taxlaw_streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - fastapi
    environment:
      - PYTHONUNBUFFERED=1

networks:
  default:
    name: taxlaw_net
