# FastAPI Service Dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential

# Copy project files
COPY . .

# Install dependencies

#RUN pip install --upgrade pip && pip install -r requirementss.txt
RUN pip install --retries 10 --timeout 60 -r requirementss.txt


# Run FastAPI app
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
